#!/bin/bash
#Used for openshift
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

#HOME=$OPENSHIFT_DATA_DIR nohup $OPENSHIFT_DATA_DIR/nave/nave.sh use 0.8.16 \
#  $OPENSHIFT_REPO_DIR'app.js' $OPENSHIFT_INTERNAL_PORT $OPENSHIFT_INTERNAL_IP \
#  > $OPENSHIFT_LOG_DIR/app.log 2>&1 &

#nohup $OPENSHIFT_REPO_DIR/diy/scripts/web-server.js > $OPENSHIFT_HOMEDIR/diy-0.1/logs/angular-server.log 2>&1 &

#HOME=$OPENSHIFT_DATA_DIR nohup $OPENSHIFT_DATA_DIR/nave/nave.sh use 0.8.16 \
#  OPENSHIFT_REPO_DIR/diy/scripts/web-server.js > $OPENSHIFT_HOMEDIR/diy-0.1/logs/angular-server.log 2>&1 &

#HOME=$OPENSHIFT_DATA_DIR nohup npm install http-server -g
#$OPENSHIFT_REPO_DIR/diy/scripts/web-server.js
#http-server -p $OPENSHIFT_INTERNAL_PORT -a $OPENSHIFT_INTERNAL_IP

cd $OPENSHIFT_REPO_DIR/diy/app
#./../scripts/web-server.js $OPENSHIFT_INTERNAL_PORT $OPENSHIFT_INTERNAL_IP
nohup ./../scripts/web-server.js $OPENSHIFT_INTERNAL_PORT $OPENSHIFT_INTERNAL_IP > $OPENSHIFT_HOMEDIR/diy-0.1/logs/web-server.log 2>&1 &

#./web-server.js $OPENSHIFT_INTERNAL_PORT $OPENSHIFT_INTERNAL_IP

