#!/bin/bash
# The logic to stop your application should be put in this script.
# Used for openshift
kill `ps -ef | grep web-server.js | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
kill `ps -ef | grep node.js | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
